### ISSUE TITLE
package name: change to something that makes it clear that this package doesn't encode the sourmash functionality in R, but consumes the outputs of sourmash and does stuff to them

### ISSUE THREAD

**Issue by taylorreiter** [Arcadia-Science/sourmashRutils#6]
Following convention, I'd like to avoid putting punctuation in the name.

**Names that don't make it clear that this package does not re-implement the core sourmash functionality**
* rourmash
* sourmashR
* souRmash (also this one is bad because bc it's basically the same as sourmash)

**Names that are a catchall**
* sourmashRutils

**Maybe better ideas**
* sourmashconsumR

**Comment by elizabethmcd** [comment]
I like sourmashconsumR! Catchy and makes it a bit more obvious it's distinguishable from core sourmash

**Comment by taylorreiter** [comment]
closed by #12
